In [90]:
import pandas as pd

In [91]:
products_df = pd.read_csv("products.csv", sep=",")
products_df.head(600)

,Unnamed: 0,id,product_name,category,product_description,price,location
0,0,243809c0-9cfc-4486-ad12-3b7a16605ba9,"Mirror wall art | in Wokingham, Berkshire | Gu...","Home & Garden / Dining, Living Room Furniture ...","Mirror wall art. Posted by Nisha in Dining, Li...",£5.00,"Wokingham, Berkshire"
1,1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,"Stainless Steel Food Steamer | in Inverness, H...",Home & Garden / Other Household Goods,Morphy Richard’s (model no 48755)Stainless ste...,£20.00,"Inverness, Highland"
2,2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,"Sun loungers | in Skegness, Lincolnshire | Gum...",Home & Garden / Garden & Patio / Outdoor Setti...,I have 2 of these - collection only as I don’t...,£20.00,"Skegness, Lincolnshire"
3,3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,"Home & Garden / Dining, Living Room Furniture ...",Great reclaimed army ammunition box used as co...,£115.00,"Radstock, Somerset"
4,4,16dbc860-696e-4cda-93f6-4dd4926573fb,Modern Shannon Sofa for sale at low cost | in ...,"Home & Garden / Dining, Living Room Furniture ...",New Design Shannon Corner sofa 5 Seater Avail...,NaN,NaN
...,...,...,...,...,...,...,...
595,293,a4d26de4-e697-4efd-81c2-2db2adcd84a5,DIVAN BEDS ALL MADE TO ORDER ON SALE NOW!!!FRE...,Home & Garden / Beds & Bedroom Furniture / Oth...,CASH ON DELIVERYFREE DELIVERYALL MADE TO ORDER...,£60.00,"Selby, North Yorkshire"
596,294,917f4bea-d031-4899-83dd-a10a19da3da9,PC speakers. Very good condition. Brand new bo...,Home & Garden / Other Household Goods,PC speakers. Large subwoofer speaker and surro...,£40.00,"Coventry, West Midlands"
597,295,cac08349-9c5c-4372-b426-ba40ed29b2ff,30 square metres of paving slabs delivered in ...,Home & Garden / Garden & Patio / Garden Buildi...,Our 600mm x 450mm slabs are used here to creat...,NaN,NaN
598,.,NaN,NaN,NaN,NaN,NaN,NaN
599,Any quantity available anywhere in Northern Ir...,NaN,NaN,NaN,NaN,NaN,NaN

In [92]:
# assigns operation to dataframe variable
products_df = products_df.dropna() # deletes columns where at least 1 item is missing

In [93]:
# cheks that NaN columns have been dropped
products_df.head(60)

,Unnamed: 0,id,product_name,category,product_description,price,location
0,0,243809c0-9cfc-4486-ad12-3b7a16605ba9,"Mirror wall art | in Wokingham, Berkshire | Gu...","Home & Garden / Dining, Living Room Furniture ...","Mirror wall art. Posted by Nisha in Dining, Li...",£5.00,"Wokingham, Berkshire"
1,1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,"Stainless Steel Food Steamer | in Inverness, H...",Home & Garden / Other Household Goods,Morphy Richard’s (model no 48755)Stainless ste...,£20.00,"Inverness, Highland"
2,2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,"Sun loungers | in Skegness, Lincolnshire | Gum...",Home & Garden / Garden & Patio / Outdoor Setti...,I have 2 of these - collection only as I don’t...,£20.00,"Skegness, Lincolnshire"
3,3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,"Home & Garden / Dining, Living Room Furniture ...",Great reclaimed army ammunition box used as co...,£115.00,"Radstock, Somerset"
12,5,5707be4f-49d9-4feb-b2c8-aa0868405c65,"Spotlights | in Newent, Gloucestershire | Gumtree",Home & Garden / Other Household Goods,New in box not needed Spotlights . Posted by s...,£9.00,"Newent, Gloucestershire"
13,6,d2244a7b-aef4-4495-aff7-0c55bf512d6e,💥💥White Wardrobe💥💥Brand new Wardrobe For sale ...,Home & Garden / Beds & Bedroom Furniture / War...,🌈🌈Call Dustin 0208-0049437\r\n🌈🌈Same Day Or a...,£419.00,"Huddersfield, West Yorkshire"
14,7,485edc04-7bbc-430a-9430-f05a77f5a917,"Letter cage | in Newent, Gloucestershire | Gum...",Home & Garden / Other Household Goods,Selling for family member brand new too big fo...,£10.00,"Newent, Gloucestershire"
15,8,7e538445-c75e-4802-8dc5-a9083a802278,"Double Pine Bed Frame | in Lytham St Annes, La...",Home & Garden / Beds & Bedroom Furniture / Dou...,Double Pine bed frame good condition. Reasonab...,£50.00,"Lytham St Annes, Lancashire"
16,9,1a64843d-72f3-4141-946f-fa9b978fe755,Solid pine dining table and chairs | in West K...,"Home & Garden / Dining, Living Room Furniture ...",Distressed solid pine table and 4 chairs In ex...,£200.00,"West Kilbride, North Ayrshire"
17,10,ac514199-1ceb-4703-902d-4d8c55bea7e4,Vortex plush velvet corner or 3+2 sofa avialbl...,"Home & Garden / Dining, Living Room Furniture ...",corner Dimension:Width is 212cm x 164cmHeight ...,£449.00,"Wigan, Manchester"
18,11,f36672f9-fbe5-40ac-8f5d-015c660c3304,"Storage unit | in Midway, Derbyshire | Gumtree",Home & Garden / Other Household Goods,Storage unit book shelf please see the photos ...,£15.00,"Midway, Derbyshire"
19,12,5f5f57d7-778f-4336-bb10-b43863418c8c,"King Size Pine Bedframe | in Hove, East Sussex...",Home & Garden / Beds & Bedroom Furniture / Oth...,"Pine king sized Bedframe, originally from Ikea...",£100.00,"Hove, East Sussex"
20,13,c2c8949f-3cde-4651-a234-4a4a1b2a9ad4,Decorative black iron water pump and sump pump...,Home & Garden / Garden & Patio / Outdoor Setti...,Working water pump and sump pump. Has been use...,£100.00,"Loughborough, Leicestershire"
21,14,8292aa4e-7f1b-4655-bf0e-f1f2c9e3ffaf,"Marquee & Gazebo Hire | in Downpatrick, County...",Home & Garden / Garden & Patio / Outdoor Setti...,Ranges of sizes available Long and short term ...,£10.00,"Downpatrick, County Down"
22,15,a7500af0-25a1-447d-a67a-c575a82f0657,"SOLD. Ceiling light | in Melrose, Scottish Bor...","Home & Garden / Dining, Living Room Furniture ...",Pewter ceiling light Ceiling light. Posted by ...,£40.00,"Melrose, Scottish Borders"
23,16,53061acb-d253-41c2-8626-ea92e1f26c21,QUALITY***CALACATTA***MARBLE***CARRARA***WHITE...,Home & Garden / Kitchenware & Accessories / Ki...,1) Top Quality Granite & Quartz kitchen Workt...,£330.00,"Ealing Broadway, London"
26,18,a68bf37d-e00f-4a33-b39f-540dd1102d28,SOLD: Super King bed with storage | in Quedgel...,Home & Garden / Beds & Bedroom Furniture / Oth...,Super King bed in excellent condition. No mark...,£100.00,"Quedgeley, Gloucestershire"
29,20,b81d8d08-7da7-40f9-9558-f29a67eee189,9.1FT SWIMMING POOL BESTWAY 56411 300cm x 201c...,Home & Garden / Garden & Patio / Outdoor Setti...,Bestway Steel Pro 9'10&quot; x 6'7&quot; x 26&...,£160.00,"Stevenage, Hertfordshire"
30,21,5d562c81-c415-4b48-ab68-a5399d3a7420,Royal Worcester Poppies 20cm Diameter Flan Pie...,Home & Garden / Kitchenware & Accessories / Ta...,Royal Worcester Poppies 20cm Diameter Flan Pie...,£7.00,"Redruth, Cornwall"
31,22,0b406233-3358-4559-a859-49552e203703,Fragranced oil burner set & heart-shaped slate...,Home & Garden / Other Household Goods,A pair of heart-themed items which would make ...,£3.00,"Grange, Edinburgh"
35,24,bcb7e8c6-88d9-43b8-b082-e9b998898f4a,"Hamad L Rug | in Twickenham, London | Gumtree","Home & Garden / Dining, Living Room Furniture ...",Unique Nomadic Rug Size: 150cm X 225cm Quality...,£120.00,"Twickenham, London"
43,26,a26b234a-55f0-4afb-8649-722b76d570be,"Free Sofa Set | in Inverness, Highland | Gumtree","Home & Garden / Dining, Living Room Furniture ...","Set of 3 sofas\r\n 1 seater - D.100cm, L.100cm...",£0.00,"Inverness, Highland"
44,27,dcbe214e-cb4b-4f18-ab16-218ec12ab68b,"Love wall art picture | in Fareham, Hampshire ...","Home & Garden / Dining, Living Room Furniture ...","Brand new. Unwanted picture. Approx 90cm wide,...",£5.00,"Fareham, Hampshire"
48,29,6f228cd8-a2d6-4f23-858b-4a77a2f42d7c,"Next bunny canvas | in Fareham, Hampshire | Gu...","Home & Garden / Dining, Living Room Furniture ...",As new bunny canvas. Approx 50cm x 40cmSmoke a...,£5.00,"Fareham, Hampshire"
49,30,538b5593-1ed7-4591-b662-980915a82b4e,"nest tables | in Norwich, Norfolk | Gumtree","Home & Garden / Dining, Living Room Furniture ...",solid oak nest tables in excellent condition h...,£30.00,"Norwich, Norfolk"
50,31,2275f5f2-ee51-410c-8d85-e5923285a864,Airtight food storage container with dividers ...,Home & Garden / Other Household Goods,This is like a deep divided plate with an airt...,£5.00,"Penarth, Vale of Glamorgan"
51,32,5b58a9d7-4006-4bb1-aa45-1f231462ad42,"BRAND NEW HILTON BED | in Stoke-on-Trent, Staf...",Home & Garden / Beds & Bedroom Furniture / Dou...,BRAND NEW QUALITY HILTON BED WITH MATTRESS IN ...,£160.00,"Stoke-on-Trent, Staffordshire"
52,33,ba4968a9-5c76-49c2-a90e-e4a5b2d773ac,"Dressing table and stool | in Grimsby, Lincoln...","Home & Garden / Dining, Living Room Furniture ...",*COLLECTION ONLY*Next Home dressing table and ...,£30.00,"Grimsby, Lincolnshire"
53,34,ef9c607a-9d95-49f8-abf8-9ad03dd20fda,Cream lined curtains 90x90 sold and collected ...,"Home & Garden / Dining, Living Room Furniture ...",Cream fully lined diamond patten curtains 90 x...,£10.00,"West Derby, Merseyside"
54,35,afb515c9-40d2-4480-8921-31f6bc36bd7a,"Brand new sofas for sale | in Archway, London ...","Home & Garden / Dining, Living Room Furniture ...",**_*Offer offer offer_**WhatsApp07459183965🔥Br...,£499.00,"Archway, London"
55,36,3778d369-8b32-4c57-882f-6fd3c02c42c2,"Pair of Woltu bar stools | in Newtownards, Cou...","Home & Garden / Dining, Living Room Furniture ...",Genuine WOLTU quality stools. The matching pai...,£100.00,"Newtownards, County Down"
56,37,09349673-6b4a-465a-b232-42185d2bd959,"Microwave | in Thornaby, County Durham | Gumtree",Home & Garden / Kitchenware & Accessories / Co...,Here I have a year old microwave for sale it’s...,£10.00,"Thornaby, County Durham"
57,38,3e29ed80-ccf8-4bbc-9318-3da0d5e5e6cb,"Stainless Steel ""Thermos King"" 1.2ltr flask | ...",Home & Garden / Other Household Goods,Top of the range stainless steel (unbreakable)...,£10.00,"Long Eaton, Nottinghamshire"
58,39,e3048c01-db41-4588-b88e-833029bf82ae,February Sale offer Divan bed with mattress av...,Home & Garden / Beds & Bedroom Furniture / Sin...,💓Brand New All Beds 🛏️ Avaliable Here Please T...,£130.00,"Erdington, West Midlands"
59,40,25a5b6b5-74e6-4936-9257-73cbb32c7d8f,"Old Style Wooden Stool/Seat | in Clydebank, We...","Home & Garden / Dining, Living Room Furniture ...",Old style solid wooden stool. Great for upcyc...,£15.00,"Clydebank, West Dunbartonshire"
60,41,b4eea71f-8d06-4ccd-bb9c-93cca5fcab1f,Display Cabinet with Light | in Clacton-on-Sea...,"Home & Garden / Dining, Living Room Furniture ...","Attractive cabinet with two glass shelves, and...",£30.00,"Clacton-on-Sea, Essex"
61,42,74f5811d-b9e2-40e7-8fcc-0d19af191834,Matalan set of 2 black white Aztec tall plante...,Home & Garden / Other Household Goods,"Completely sold out online, selling as I misse...",£40.00,"Blackburn, Lancashire"
64,44,615e7b06-b976-4b68-828d-fc29f4bcd54a,"Large Garden Storage Box | in Billingham, Coun...",Home & Garden / Garden & Patio / Outdoor Setti...,Large garden storage box only 1 and a half yea...,£80.00,"Billingham, County Durham"
65,45,0a9f67fb-23c2-454a-9ed6-62e6bc2e6cc6,Brand New - Vinyl Black and White Flooring | i...,"Home & Garden / Dining, Living Room Furniture ...","This is brand new, unused.\r\nNot a mark on th...",£45.00,"Slough, Berkshire"
66,46,006580a6-a094-44e9-afae-bf0b2608f304,"Recliner chair | in Monmouth, Monmouthshire | ...","Home & Garden / Dining, Living Room Furniture ...",A pair of manual recliner chairs in a pale gre...,£60.00,"Monmouth, Monmouthshire"
67,47,6351baeb-33eb-4ba9-b7c0-aba4bae11552,Quooker Fusion Square Chrome Pro 3 vaq | in No...,Home & Garden / Other Household Goods,"Instant 100 degree boiling water,all from ONE ...",£400.00,"Notting Hill, London"
68,48,45acbefc-7f24-41ff-af59-374c13b8d9b6,**100% GUARANTEED PRICE!**BRAND NEW-Double Bed...,Home & Garden / Beds & Bedroom Furniture / Dou...,****Please click ;See all ads; on Right top Co...,£189.99,"Acton, London"
69,49,39e6b9eb-4320-4f89-a401-55b6fc39bddf,Vintage Pine Scrubtop Farmhouse Table. | in Wa...,"Home & Garden / Dining, Living Room Furniture ...",Stunning Vintage Pine Farmhouse Scrubtop Table...,£95.00,"Wakefield, West Yorkshire"
70,50,b862b005-b11d-4b9b-88d9-c5d50c907c1f,"Ikea Ektorp Armchair in grey | in Kingston, Lo...","Home & Garden / Dining, Living Room Furniture ...",As new Ikea Ektorp armchair with charcoal grey...,£120.00,"Kingston, London"
71,51,6277f04e-7cbd-480a-9990-61c9525ebea1,"Vintage Winstanley Cat | in Mansfield, Notting...","Home & Garden / Dining, Living Room Furniture ...",Early Signed Winstanley ginger cat. Size 3\r\n...,£19.00,"Mansfield, Nottinghamshire"
72,52,2e6db1e3-b60d-456a-8320-ddf4827e464f,February Sale offer Divan bed with mattress av...,Home & Garden / Beds & Bedroom Furniture / Sin...,💓Brand New All Beds 🛏️ Avaliable Here Please T...,£130.00,"Nechells, West Midlands"
84,54,3363e551-9da1-4032-ac58-f4928b848205,2 Smala Ligne Roset Daybed Sofas | in Sydenham...,"Home & Garden / Dining, Living Room Furniture ...","2 Smala Ligne Roset Daybed Sofas, these have w...","£1,900.00","Sydenham, London"
85,55,253c59ca-2bcf-4f96-85d9-99a74ff16e7f,"CURTAINS AND CUSHIONS | in Bangor, County Down...","Home & Garden / Dining, Living Room Furniture ...",Professionally made curtains fully lined with ...,£65.00,"Bangor, County Down"
86,56,470bde59-0755-4527-924e-a03a48375ded,"Lounge Curtains | in Stroud, Gloucestershire |...","Home & Garden / Dining, Living Room Furniture ...","Patterned, green, grey and white lined lounge ...",£50.00,"Stroud, Gloucestershire"
87,57,931968ce-4309-4a1b-8cdc-4fac14dfb6af,"Kitchen/Dining Table | in Dyce, Aberdeen | Gum...","Home & Garden / Dining, Living Room Furniture ...",Solid wood kitchen table in very good conditio...,£300.00,"Dyce, Aberdeen"
88,58,a4246b1c-962a-414d-965c-fd36da0a6415,Brand New All Sizes Divan Bed Base With Any Ty...,Home & Garden / Beds & Bedroom Furniture / Dou...,FREE DELIVERY ! WAREHOUSE CLEARANCE! 100% CHEA...,£59.00,"Brighton, East Sussex"
89,59,d60b8a85-0b91-40a9-82dd-07c08c55dce9,"Cream rug | in Southampton, Hampshire | Gumtree","Home & Garden / Dining, Living Room Furniture ...","Ikea rug, measures 135c195cm. In used but fair...",£30.00,"Southampton, Hampshire"
96,61,1ad84a76-8f50-4069-813d-43f6edb48a0f,"Bistro tables and chairs | in Hamilton, South ...","Home & Garden / Dining, Living Room Furniture ...",2 aluminium tables and 7 chairs for sale. Will...,£60.00,"Hamilton, South Lanarkshire"
97,62,cedbf235-b6e4-4a54-98c6-6a02e6aeba52,Antique vintage gold Mirror - amazing feature ...,"Home & Garden / Dining, Living Room Furniture ...","Vintage gold leaf covered mirror, much loved, ...",£50.00,"Camberwell, London"
98,63,cc756d52-64c9-4dd5-81af-a4e62fa6bd4a,Pretty Jonelle curtains w 66 D 53 - 54 inches ...,"Home & Garden / Dining, Living Room Furniture ...",These Jonelle polycotton curtains have a prett...,£10.00,"Portishead, Bristol"
99,64,fb5f19a5-6137-4e43-8629-c36ad4eb4981,"Set of 3 glass coffee tables | in Newcastle, T...","Home & Garden / Dining, Living Room Furniture ...",A set of three glass coffee tables on curved m...,£120.00,"Newcastle, Tyne and Wear"
100,65,a33f8af2-093e-40e3-b86c-477c3addb431,February Sale offer Divan bed with mattress av...,Home & Garden / Beds & Bedroom Furniture / Sin...,💓Brand New All Beds 🛏️ Avaliable Here Please T...,£130.00,"Nechells, West Midlands"
101,66,fa9c0d7a-cb7f-43d9-9654-9c44561a093e,"Table and chairs | in Ormeau Road, Belfast | G...","Home & Garden / Dining, Living Room Furniture ...",Glass dining table and four chairs for sale. L...,£100.00,"Ormeau Road, Belfast"
105,68,c0e5ef79-09c0-4cb7-9b7c-edd3d53aa530,2 x new jugg nutri pouch systems *£5 for both*...,Home & Garden / Other Household Goods,From a clean smoke free home 2 x new jugg nutr...,£5.00,"Kirkcaldy, Fife"
113,70,82f09c12-a151-450e-923e-12c2ea83fbb2,"Coffee table | in Crewe Toll, Edinburgh | Gumtree","Home & Garden / Dining, Living Room Furniture ...","Solid pine coffee table ,with slim wooden leg...",£20.00,"Crewe Toll, Edinburgh"

In [94]:
products_df.dtypes #finds the object type for each column

Unnamed: 0             object
id                     object
product_name           object
category               object
product_description    object
price                  object
location               object
dtype: object

In [95]:
products_df.info() # finds the object types and number of nulls

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6311 entries, 0 to 11317
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           6311 non-null   object
 1   id                   6311 non-null   object
 2   product_name         6311 non-null   object
 3   category             6311 non-null   object
 4   product_description  6311 non-null   object
 5   price                6311 non-null   object
 6   location             6311 non-null   object
dtypes: object(7)
memory usage: 394.4+ KB

In [96]:
# price column needs to be converted as a float
# if we try to sum objects, we don't get the expected result

# products_df['price'].sum() # throws error

In [97]:
products_df['price'] = products_df['price'].str.strip('£')
products_df = products_df.replace(',','', regex=True) # commas need to go to convert price string to float
products_df['price'] = products_df['price'].astype('float64')

In [98]:
products_df.head()

,Unnamed: 0,id,product_name,category,product_description,price,location
0,0,243809c0-9cfc-4486-ad12-3b7a16605ba9,Mirror wall art | in Wokingham Berkshire | Gum...,Home & Garden / Dining Living Room Furniture /...,Mirror wall art. Posted by Nisha in Dining Liv...,5.0,Wokingham Berkshire
1,1,1c58d3f9-8b93-47ea-9415-204fcc2a22e6,Stainless Steel Food Steamer | in Inverness Hi...,Home & Garden / Other Household Goods,Morphy Richard’s (model no 48755)Stainless ste...,20.0,Inverness Highland
2,2,860673f1-57f6-47ba-8d2f-13f9e05b8f9a,Sun loungers | in Skegness Lincolnshire | Gumtree,Home & Garden / Garden & Patio / Outdoor Setti...,I have 2 of these - collection only as I don’t...,20.0,Skegness Lincolnshire
3,3,59948726-29be-4b35-ade5-bb2fd7331856,Coffee side table from Ammunition ammo box hai...,Home & Garden / Dining Living Room Furniture /...,Great reclaimed army ammunition box used as co...,115.0,Radstock Somerset
12,5,5707be4f-49d9-4feb-b2c8-aa0868405c65,Spotlights | in Newent Gloucestershire | Gumtree,Home & Garden / Other Household Goods,New in box not needed Spotlights . Posted by s...,9.0,Newent Gloucestershire

In [99]:
# checks that the prices are now floats
products_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6311 entries, 0 to 11317
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           6311 non-null   object
 1   id                   6311 non-null   object
 2   product_name         6311 non-null   object
 3   category             6311 non-null   object
 4   product_description  6311 non-null   object
 5   price                6311 non-null   float64
 6   location             6311 non-null   object
dtypes: float64(1), object(6)
memory usage: 394.4+ KB